#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-org.eclipse.sisu.inject
Version  : 0.3.3
Release  : 2
URL      : https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3/org.eclipse.sisu.inject-0.3.3.jar
Source0  : https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3/org.eclipse.sisu.inject-0.3.3.jar
Source1  : https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.jar
Source2  : https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.pom
Source3  : https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3/org.eclipse.sisu.inject-0.3.3.pom
Source4  : https://repo1.maven.org/maven2/org/eclipse/sisu/sisu-inject/0.3.3/sisu-inject-0.3.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause EPL-1.0
Requires: mvn-org.eclipse.sisu.inject-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-org.eclipse.sisu.inject package.
Group: Data

%description data
data components for the mvn-org.eclipse.sisu.inject package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/sisu-inject/0.3.3
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/sisu/sisu-inject/0.3.3


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.jar
/usr/share/java/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.pom
/usr/share/java/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3/org.eclipse.sisu.inject-0.3.3.jar
/usr/share/java/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3/org.eclipse.sisu.inject-0.3.3.pom
/usr/share/java/.m2/repository/org/eclipse/sisu/sisu-inject/0.3.3/sisu-inject-0.3.3.pom
